# Introduction {#intro}

`r if(identical(gitbook_on, FALSE))knitr::asis_output(paste0("This report is available as pdf and as an online interactive report at ", params$report_url, ". We recommend viewing online as the web-hosted html version contains more features and is more easily navigable."))`

`r if(identical(gitbook_on, FALSE)){knitr::asis_output("<br>")}`

Since 2020, the Society for Ecosystem Restoration Northern British Columbia (SERNbc) has been actively involved in planning, coordinating, and conducting fish passage restoration efforts within the Bulkley River and Morice River watershed groups, which are sub-basins of the Skeena River watershed. In 2022, the study area was expanded to include the Zymoetz River watershed group and the Kispiox River watershed group, followed by an extension in 2023 to encompass sections of the Kitsumkalum River watershed group, particularly where Highway 16 intersects the watershed.

<br>

The primary objective of this project is to identify and prioritize fish passage barriers within these study areas,
develop comprehensive restoration plans to address these barriers, and foster momentum for broader ecosystem restoration
initiatives. While the primary focus is on fish passage, this work also serves as a lens through which to view the
broader ecosystems, leveraging efforts to build capacity for ecosystem restoration and improving our understanding of
watershed health. We recognize that the health of life - such as our own - and the health of our surroundings are
interconnected, with our overall well-being dependent on the health of our environment.

<br>

Although the main purpose of this report is to document 2023 field work data and results, it also builds on reporting 
from field activities conducted from 2020 to 2022. In addition to the numerous assessments at sites undocumented in past
years of the project, field activities were also conducted at 10 sites where habitat confirmations
were previously documented as per the report links below. The reports for these sites were edited and updated with 2023 data.

- [Bulkley River and Morice River Watershed Groups Fish Passage Restoration Planning (2020)](https://newgraphenvironment.github.io/fish_passage_bulkley_2020_reporting/)
- [Bulkley River and Morice River Watershed Groups Fish Passage Restoration Planning 2021](https://newgraphenvironment.github.io/fish_passage_skeena_2021_reporting/)
- [Bulkley River Watershed Fish Passage Restoration Planning 2022](https://newgraphenvironment.github.io/fish_passage_bulkley_2022_reporting/)
- [Skeena Watershed Fish Passage Restoration Planning 2022](https://newgraphenvironment.github.io/fish_passage_skeena_2022_reporting/)


<br>

Please note that at the time of reporting, this document was a living document changing over time.  Version numbers are
logged for each release with modifications, enhancements and other changes tracked with the "Changlog" section.
Additionally, issues and planned enhancements are tracked
[here](https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/issues).

<br>


The health and viability of freshwater fish populations can depend on access to tributary and off channel areas which
provide refuge during high flows, opportunities for foraging, overwintering habitat, spawning habitat and summer rearing
habitat [@bramblett_etal2002SeasonalUse; @swalesRoleOffChannelPonds1989; @diebel_etal2015EffectsRoad].  Culverts can
present barriers to fish migration due to low water depth, increased water velocity, turbulence, a vertical drop at the
culvert outlet and/or maintenance issues [@slaneyFishHabitatRehabilitation1997; @cote_etal2005Fishpassage]. As road
crossing structures are commonly upgraded or removed there are numerous opportunities to restore connectivity by
ensuring that fish passage considerations are incorporated into repair, replacement, relocation and deactivation
designs.

<br>

Although remediation and replacement of stream crossing structures can have benefits to local fish populations, the
costs of remedial works can be significant and the impacts of the work often complex to evaluate and quantify.
Additionally, allocation of ecosystem restoration funding towards infrastructure upgrades on transportation right of
ways are not always considered ethical under all circumstances from all perspectives. When funds are finite and invested
groups are engaged in fund raising, cost benefits and the ethics of crossing replacements should be explored
collaboratively alongside the cost benefits and ethics of alternative investment activities including transportation
corridor relocation/deactivation, land procurement/covenant, cattle exclusion, riparian/floodplain restoration, habitat
complexing, water conservation,  commercial/recreational fishing management, salt water interventions and research.
