# Recommendations

A major challenge in advancing fish passage restoration is the complexity of working across jurisdictions and with multiple stakeholders—rail and highway authorities, forestry ministries, licensees, and private landowners. These partners are often being asked to accommodate priorities that originate outside their mandates and budgets. Convincing them to invest in difficult, high-cost interventions—like modifying crossings or relocating infrastructure—requires navigating uncertainty about costs and ecological outcomes, as well as a disconnect between the benefits to watershed health and the internal pressures or performance goals of these agencies. It’s a tough ask: to take on massive, uncertain projects when they’re already stretched thin with their own responsibilities.

<br>

Fish passage restoration within the Skeena and across British Columbia is further complicated by the legacy of infrastructure deeply embedded in the landscape. Roads, railways, highways, community infrastructure and private assets often constrain floodplains and disrupt natural hydrological processes. While targeted repairs to individual barriers are essential, they won’t resolve the broader systemic issues without rethinking and restructuring how infrastructure interacts with watershed function. Loss of riparian vegetation and intensive beaver management only add to the degradation. Addressing these challenges means making strategic, well-communicated choices—picking battles carefully, building trust, and staying committed to a longer-term transformation.

<br>

While preliminary top remediation priorities are provided by watershed group, these rankings are inherently subjective and can depend on the capacity and willingness of infrastructure owners and tenure holders to support implementation—both financially and over the often multi-year project timelines. In practice, we must often act opportunistically, pursuing simpler, lower-cost options to maintain momentum and achieve near-term progress.

<br>

Government, community groups, landowners, non-profits, industry and other stakeholders should work collaboratively to address high and moderate priority barriers identified `r if(identical(gitbook_on, FALSE)){knitr::asis_output(paste0("online within the Results and Discussion section of the report found ", ngr::ngr_str_link_url(url_base = params$report_url, anchor_text = "here")))}else{knitr::asis_output("in Table \\@ref(tab:tab-sites-cap)")}`. Although the table presents many options, linked reports specify whether each site is a low, moderate, or high priority. Progress on any front is meaningful, and aiming to remediate at least one high-priority site per year per watershed group—regardless of its overall rank—is a practical and effective approach.


Recommendations for potential incorporation into collaborative watershed connectivity planning include:

- Government, community groups, landowners, and other stakeholders should work collaboratively to address highest ranked
barriers identified `r if(identical(gitbook_on, FALSE)){knitr::asis_output(paste0("online within the Results and Discussion section of the report found ", ngr::ngr_str_link_url(url_base = params$report_url, anchor_text = "here")))}else{knitr::asis_output("in Table \\@ref(tab:tab-sites-cap)")}`. While the table presents a wide range of options, the linked 
individual reports indicate whether each site is a low, moderate, or high priority. Progress on any front is valuable, 
and aiming to remediate at least one high-priority site per year per watershed group—regardless of its overall rank—is a practical and effective approach.

- Continue collaborating with Gitksan Watershed Authorities and Skeena Fisheries Commission to implement fish passage restoration at Waterfall Creek – PSCIS 124421 (11th Avenue, New Hazelton) within the Bulkley River watershed group. Lessons from the successful 2024 replacement of crossing 198217 on a Skeena River tributary near Sik-e-dakh Water Tower Road can now inform work at Waterfall Creek. Restoration here has a rich history with coho transplants by the Chicago Creek Community Environmental Enhancement Society beginning in 1990 [donas2022MissionCreek]. Despite impacts from urban and industrial development, the greater Station/Mission Creek watershed offers strong potential for public engagement and ecosystem function gains. Collaborative efforts—led by Gitksan Watershed Authorities, Chicago Creek Community Environmental Enhancement Society, Skeena Fisheries Commission, Fisheries and Oceans Canada, SERNbc and 
others aim to build on 2024 engineering designs and fieldwork to advance these goals in collaboration with the District of New Hazelton, CN Rail, 
Ministry of Transportation,  Kispiox Band,  Gitksan House representatives, Skeena Watershed Conservation Coalition and others.

- PSCIS crossing 197378 is located on a tributary to Owen Creek along Klate Lake Road, within the Morice River Watershed Group area. 
Through 2024 project activities - the site now has a completed design, with a proposed replacement of the existing 1.0m culvert with a 12m free-span bridge. We recommend moving forward by coordinating with the Bii Wenii Kwa Restoration/Recovery Plan to secure funding, define delivery partners, and schedule implementation. This initiative brings together the Wet’suwet’en Treaty Society, Fisheries and Oceans Canada, BC Ministry of Forests, Water, Land and Resource Stewardship, Morice Water Monitoring Trust, and Northwest Research and Monitoring to support collaborative, priority-driven habitat restoration across the watershed.


- Integrate fish passage restoration planning with other restoration and enhancement initiatives in the region to
maximize benefits to fish populations as well as for communities within the Skeena River watershed.  This includes
working with the Gitskan Watershed Authorities (GWA), Skeena Fisheries Commission, Skeena Watershed Conservation Coalition, 
Wet'suwet'en Treaty Society, Morice Watershed Monitoring Trust, Fisheries and Oceans Canada, Provincial Regulators, Bulkley Valley Research Centre,
 the Environmental Stewardship Initiative (Skeena Sustainability Assessment Forum) and
others to leverage funding, knowledge and resources for fish passage restoration towards other projects related to
watershed health in the region. Examples of where this is already taking place is leveraging of Morice River watershed
group fish passage sites into the Bii Wenii Kwa Restoration/Recovery Plan and
incorporation of Upper Bulkley River sites into the [Neexdzii Kwah Restoration Planning](https://newgraphenvironment.github.io/restoration_wedzin_kwa_2024) [@irvine_schick2025NeexdziiKwah].

- Continue to refine the prioritization tools using the metrics established in reporting since 2024—such as habitat quality, habitat quantity, species presence, remediation cost, and other relevant factors. Integrate these metrics into a more accessible format by linking interactive mapping outputs to the filterable table presented in the results section of this report. Continue to update and clarify individual site memos, incorporating additional contextual information to improve cross-stakeholder communication and facilitate funding and implementation efforts.
 
- Develop strategies to explore cost and fisheries production benefits of stream crossing structure upgrades alongside
alternative/additional restoration and enhancement investments such as land conservation/procurement/covenant, cattle
exclusion, riparian restoration, habitat complexing, water conservation, commercial/recreational fishing management,
water treatment and research. Ideentify and pursue opportunities to collaborate and leverage initiatives together in
study area watersheds (ex. fish passage rehabilitation, riparian restoration and cattle exclusion) for maximum likely
restoration benefits.
