# Changelog {-}

### Skeena Watershed Fish Passage Restoration Planning 2024 - Development {-} {-}


### Skeena Watershed Fish Passage Restoration Planning 2024 - 0.1.3 (20250613) {-} {-}
  - remove uav info from the summary tables as that info is now in its own table


### Skeena Watershed Fish Passage Restoration Planning 2024 - 0.1.2 (20250423) {-} {-}
  - 3 level table of contents in gitbook
  - add summary of modelling outputs for sites assessed to results
  - Update Comeau map
  - Update hydrographs to new theme
  - Fish plots in theme_bw


### Skeena Watershed Fish Passage Restoration Planning 2024 - 0.1.1 (20250331) {-} {-}
  - Add recommendations to executive summary
  - Add discussion points to the recommendation section


### Skeena Watershed Fish Passage Restoration Planning 2024 - 0.1.0 (20250330) {-} {-}

  - Add executive summary
  - Add recommendations
  - incorperate top ranked sites from each watershed group to summary table in results
  - Rework methods and results
  - Move Buck Falls to appendix
  - Rename Gershwin to Comeau
  - Add maps to Comeau and Gershwin
  - Rework Comeau

### Skeena Watershed Fish Passage Restoration Planning 2024 - 0.0.1 {-} {-}

- *2025-02-04*  
  - Initial draft of the 2024 report.
